config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '/(:locale)', constraints: {locale: /en|fr/} do
    root 'pages#home'
    get 'kits' => 'pages#kits', as: :kits
    get 'ingredients' => 'pages#ingredients', as: :ingredients
    get 'history' => 'pages#history', as: :history
    get 'faq' => 'pages#faq', as: :faq
    get 'recipe' => 'pages#recipe', as: :recipe
  	get 'workshop' => 'pages#workshop', as: :workshop
    get 'workshop-entreprise' => 'pages#workshopentreprise', as: :workshopentreprise
  	get 'enterprise' => 'pages#enterprise', as: :enterprise
  	get 'order' => 'pages#order', as: :order
    get 'subscribed' => 'pages#subscribed', as: :subscribed
    get 'about' => 'pages#about', as: :about
    resources :charges
    get 'thanks', to: 'charges#thanks', as: 'thanks'
  end
  get '/:locale' => 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter do
    if request.ssl? && Rails.env.production?
      redirect_to "http://#{request.host_with_port}#{request.fullpath}", :status => :moved_permanently
    end
  end

  before_action :set_locale
   # To set different languages for the site
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    options = options.merge({ locale: I18n.locale })
    options = options.merge({ subdomain: 'www' }) if Rails.env.heroku_prod?
    options
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :address => params[:order_address],
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,
      amount:       params[:amount],
      description:  'Bake Ta Baguette',
      currency:     'eur'
    )

    UserMailer.booking_confirmation(params[:stripeEmail]).deliver

    redirect_to thanks_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end

  def thanks
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def kits
	end

	def history
	end

	def faq
	end

	def recipe
	end

	def order
	end

	def workshop
	end

	def workshopenterprise
	end

	def about
	end

	def ingredients
	end

	def subscribed
    UserMailer.subscribe_confirmation(params[:email]).deliver
    UserMailer.subscribe(params[:email]).deliver
    redirect_to :action => "home"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/charges/thanks.html.erb
<body class="pages-home">
  <%= render './layouts/navbar' %>

  Thank you for your order! You should receive an email in the next 2 minutes!
  
  <%= render './layouts/footer' %>
</body>

app/views/layouts/_footer.html.erb
 <div id="footer">
  <div class="container">
    <div data-react-class="NewsletterForm">
      <div data-reactroot class="newsletter">
        <h2><%= raw t 'footer.subscribe' %></h2>
        <p><%= raw t 'footer.subscribe_subtitle' %></p>

        <%= form_tag({controller: "pages", action: "subscribed"}, method: "get") do %>
          <div class="newsletter-input">
            <%= email_field_tag :email, nil, placeholder: "you@gmail.com", name: "email", required: "required",  class: "newsletter-input-email" %>
            <%= submit_tag(t('footer.subscribe_button'), class: "newsletter-input-button") %>
          </div>
        <% end %>

      </div>
    </div>
    <div class='brand-footer'>
<!--         <img src="logo.png" alt="logo baketabaguette" class="logo-baguette">
--> </div>
    <div class="flex">
      <div class='footer-section'>
        <h3>
          <%= raw t 'footer.section1' %>
        </h3>
        <div class='footer-section-links'>
          <div>
            <a href="#" target='_blank'>
            <%= raw t 'footer.section1_1' %>
            </a>
          </div>
        </div>
      </div>
      <div class='footer-section'>
        <h3>
          <%= raw t 'footer.section2' %>
        </h3>
        <div class='footer-section-links'
          >
          <div>
            <a href="">
            <%= raw t 'footer.section2_1' %>
            </a>            
          </div>
          <div>
            <%= link_to t('footer.section2_2'), kits_path %>
          </div>
          <div>
            <%= link_to t('footer.section2_3'), workshop_path %>          
          </div>
        </div>
      </div>
      <div class='footer-section'>
        <h3>
          <%= raw t 'footer.section3' %>
        </h3>
        <div class='footer-section-links'>
          <div>
            <%= link_to t('footer.section3_1'), about_path %>
          </div>
          <div>
            <a href="mailto:baketabaguette@gmail.com"><%= raw t 'footer.section3_3' %></a>
          </div>
        </div>
      </div>
      <div class='footer-section'>
        <h3>
          <%= raw t 'footer.section4' %>
        </h3>
        <div class='footer-section-links'>
          <div>
            <a href="https://www.facebook.com/baketabaguette" target="_blank"><%= raw t 'footer.section4_1' %></a>
          </div>
          <div>
            <a href="https://www.instagram.com/baketabaguette/" target="_blank"><%= raw t 'footer.section4_3' %></a>
          </div>
          <div>
            <a href="https://twitter.com/baketabaguette" target="_blank"><%= raw t 'footer.section4_2' %></a>
          </div>
          <div>
            <a href="https://www.tripadvisor.fr/Attraction_Review-g187147-d12588005-Reviews-Bake_Ta_Baguette-Paris_Ile_de_France.html" target="_blank"><%= raw t 'footer.section4_4' %></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- IUBENDA COOKIE TRACKING -->
<!-- INTERCOM -->
<!-- TO DO -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-100784983-1', 'auto');
  ga('send', 'pageview');
</script>
<!-- END -->
<!-- MIXPANEL, FB PIXELS, HOTJAR SETTINGS -->

app/views/layouts/_navbar.html.erb
<nav class="navbar-baguette navbar-baguette-white">
  <div class="container navbar-baguette-container">
    <div class='navbar-baguette-side'>
      <div class="dropdown hidden-md hidden-lg">
        <a class='navbar-baguette-link-menu-wrapper' type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <div class='navbar-baguette-link-menu'></div>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li class='main'><%= link_to t('navbar.kits'), kits_path %></li>
          <li class='main'><%= link_to t('navbar.recipe'), recipe_path %></li>
          <li class='main'><%= link_to t('navbar.ingredients'), ingredients_path %></li>
          <li class='main'><%= link_to t('navbar.history'), history_path %></li>
          <li class='main'><%= link_to t('navbar.faq'), faq_path %></li>
          <li class='main'><%= link_to t('navbar.workshop'), workshop_path %></li>
          <li class='main hidden-md hidden-lg'><%= link_to t('navbar.order'), order_path %></li>
          <li class="main hidden-md hidden-lg">
            <div class="flags-smartphone">
              <a style="opacity: .3" href="/fr">
                <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                  <g>
                    <rect fill="#FFFFFF" width="56" height="40"/>
                    <rect fill="#3B6AC3" width="18" height="40"/>
                    <rect x="38" fill="#FF0000" width="18" height="40"/>
                  </g>
                </svg>
              </a>
              <a href="/">
                <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                  <g>
                    <rect fill="#001468" width="56" height="40"/>
                    <path fill="#FFFFFF" d="M56,40h-6L34,27v13H22V27L6,40H0v-4l12-10H0V14h12L0,4V0h6l16,13V0h12v13L50,0h6v4L44,14h12v12H44l12,10V40
                      z"/>
                    <path fill="#FF0000" d="M53,40L36,26h5l15,13v1H53z M32,40h-8V24H0v-8h24V0h8v16h24v8H32V40z M36,14L53,0h3v1L41,14H36z M0,1V0h3
                      l17,14h-5L0,1z M20,26L3,40H0v-1l15-13H20z"/>
                  </g>
                </svg>
              </a>
            </div>
          </li>
        </ul>
      </div>
      <div class="hidden-xs hidden-sm">
        <span class='flag-container'>
          <div>
            <div class="dropdown">
              <div class="dropdown-toggle" type="button" id="languageMenuToggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                  <g>
                    <% if I18n.locale == :en %>
                      <rect fill="#001468" width="56" height="40"/>
                      <path fill="#FFFFFF" d="M56,40h-6L34,27v13H22V27L6,40H0v-4l12-10H0V14h12L0,4V0h6l16,13V0h12v13L50,0h6v4L44,14h12v12H44l12,10V40
                        z"/>
                      <path fill="#FF0000" d="M53,40L36,26h5l15,13v1H53z M32,40h-8V24H0v-8h24V0h8v16h24v8H32V40z M36,14L53,0h3v1L41,14H36z M0,1V0h3
                        l17,14h-5L0,1z M20,26L3,40H0v-1l15-13H20z"/>
                    <% elsif I18n.locale == :fr %>
                      <rect fill="#FFFFFF" width="56" height="40"/>
                      <rect fill="#3B6AC3" width="18" height="40"/>
                      <rect x="38" fill="#FF0000" width="18" height="40"/>
                    <% end %>
                  </g>
                </svg>
                <span class="caret"></span>
              </div>
              <ul class="dropdown-menu" aria-labelledby="languageMenuToggle" id="languageMenu">
                <li>
                  <%= link_to url_for(:locale => 'en' ) do %>
                    <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                      viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                      <g>
                        <rect fill="#001468" width="56" height="40"/>
                        <path fill="#FFFFFF" d="M56,40h-6L34,27v13H22V27L6,40H0v-4l12-10H0V14h12L0,4V0h6l16,13V0h12v13L50,0h6v4L44,14h12v12H44l12,10V40
                          z"/>
                        <path fill="#FF0000" d="M53,40L36,26h5l15,13v1H53z M32,40h-8V24H0v-8h24V0h8v16h24v8H32V40z M36,14L53,0h3v1L41,14H36z M0,1V0h3
                          l17,14h-5L0,1z M20,26L3,40H0v-1l15-13H20z"/>
                      </g>
                    </svg>
                    <p>English</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to url_for(:locale => 'fr' ) do %>
                    <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                      viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                      <g>
                        <rect fill="#FFFFFF" width="56" height="40"/>
                        <rect fill="#3B6AC3" width="18" height="40"/>
                        <rect x="38" fill="#FF0000" width="18" height="40"/>
                      </g>
                    </svg>
                    <p>Français</p>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </span>
      </div>
      <div class="left hidden-sm hidden-xs">
        <div class="navbar-baguette-item has-no-padding">
          <%= link_to t('navbar.kits'), kits_path, :class => "hidden-xs  navbar-baguette-link", :id => "navbar-baguette-menu" %>
          <!-- <div class="dropdown">
            <%# link_to t('navbar.kits'), kits_path, :class => "hidden-xs  dropdown-toggle navbar-baguette-link", :id => "navbar-baguette-menu", data: { toggle: 'dropdown'} %>
            <div class="dropdown-menu dropdown-menu-right dropdown-cities">
              <div class="dropdown-cities-container text-center">
                <ul class="list-unstyled">
                  <li class="title">
                    <%# raw t('navbar.parisian_kit') %>
                  </li>
                  <li>
                    <%# link_to t('navbar.parisian_kit_details'), kits_path(:anchor => "parisian"), :class => "cta-enterprise red" %>
                  </li>
                </ul>
                <ul class="list-unstyled">
                  <li class="title" style="">
                    <%# raw t('navbar.countryside_kit') %>
                  </li>
                  <li style="padding: 3px 0px;">
                    <%# link_to t('navbar.countryside_kit_details'), kits_path(:anchor => "seeds"), :class => "cta-enterprise" %>
                  </li>
                </ul>
              </div>
            </div>
          </div> -->
        </div>
        <hr class='hidden-xs'>
        <div class="navbar-baguette-item has-no-padding">
          <%= link_to t('navbar.recipe'), recipe_path, :class => "hidden-xs  navbar-baguette-link", :id => "navbar-baguette-menu" %>
        </div>
        <hr class='hidden-xs'>
        <div class="navbar-baguette-item has-no-padding">
          <%= link_to t('navbar.ingredients'), ingredients_path, :class => "hidden-xs  navbar-baguette-link", :id => "navbar-baguette-menu" %>
        </div>
        <hr class='fake-hr hidden-sm hidden-xs'>
      </div>
    </div>
    <a class="baguette-link" href="/">
      <%= image_tag('logo.png', :class => "logo-baguette", :alt => "logo baketabaguette") %>
    </a>
    <div class="navbar-baguette-side text-right hidden-sm hidden-xs">
      <hr class='fake-hr hidden-xs'>
      <%= link_to t('navbar.history'), history_path, :class => "navbar-baguette-link" %>
      <hr class='hidden-xs'>
      <div class="navbar-baguette-item has-no-padding">
        <%= link_to t('navbar.faq'), faq_path, :class => "navbar-baguette-link" %>
      </div>
      <!-- UNCOMMENT FOR WORKSHOPS RELEASE -->
      <hr class="hidden-xs">
      <%= link_to t('navbar.workshop'), workshop_path, :class => "hidden-xs  dropdown-toggle navbar-baguette-link", :id => "navbar-baguette-menu", data: { toggle: 'dropdown', text: 'Workshops'} %>
      <!-- <div class="dropdown-menu dropdown-menu-right dropdown-cities">
        <div class="dropdown-cities-container text-center">
          <ul class="list-unstyled">
            <li class="title">
              <%# raw t('navbar.workshop_individual') %>
            </li>
            <li>
              <%# link_to t('navbar.workshop_individual_details'), workshop_path, :class => "cta-enterprise red" %>
            </li>
          </ul>
          <ul class="list-unstyled">
            <li class="title" style="">
              <%# raw t('navbar.workshop_entreprise') %>
            </li>
            <li style="padding: 3px 0px;">
              <%# link_to t('navbar.workshop_entreprise_details'), workshopentreprise_path, :class => "cta-enterprise" %>
            </li>
          </ul>
        </div>
      </div> -->
      <div class="left" id="navbar-apply">
        <%= link_to t('navbar.order'), order_path, :class => "navbar-baguette-link-cta" %>
      </div>
    </div>
  </div>
  </div>
</nav>
<div class="header-fixed">
  <div class="header-inner">
    <div class="container flex align-center">
      <div class=" dropdown full-item hidden-md hidden-lg">
        <a class='navbar-baguette-link-menu-wrapper' type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <div class='navbar-baguette-link-menu'></div>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li class="main"><%= link_to t('navbar.kits'), kits_path %></li>
          <li class='main'><%= link_to t('navbar.ingredients'), ingredients_path %></li>
          <li class='main'><%= link_to t('navbar.recipe'), recipe_path %></li>
          <li class="main"><%= link_to t('navbar.history'), history_path %></li>
          <li class="main"><%= link_to t('navbar.faq'), faq_path %></li>
          <!-- <li class="main"><%# link_to t('navbar.workshop'), workshop_path %></li> -->
          <li class="main hidden-md hidden-lg"><%= link_to t('navbar.order'), order_path %></li>
          <li class="main hidden-md hidden-lg">
            <div class="flags-smartphone">
              <a style="opacity: .3" href="/fr">
                <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                  viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                  <g>
                    <rect fill="#FFFFFF" width="56" height="40"/>
                    <rect fill="#3B6AC3" width="18" height="40"/>
                    <rect x="38" fill="#FF0000" width="18" height="40"/>
                  </g>
                </svg>
              </a>
              <a href="/">
                <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                  viewBox="0 0 56 40" enable-background="new 0 0 56 40" xml:space="preserve">
                  <g>
                    <rect fill="#001468" width="56" height="40"/>
                    <path fill="#FFFFFF" d="M56,40h-6L34,27v13H22V27L6,40H0v-4l12-10H0V14h12L0,4V0h6l16,13V0h12v13L50,0h6v4L44,14h12v12H44l12,10V40
                      z"/>
                    <path fill="#FF0000" d="M53,40L36,26h5l15,13v1H53z M32,40h-8V24H0v-8h24V0h8v16h24v8H32V40z M36,14L53,0h3v1L41,14H36z M0,1V0h3
                      l17,14h-5L0,1z M20,26L3,40H0v-1l15-13H20z"/>
                  </g>
                </svg>
              </a>
            </div>
          </li>
        </ul>
      </div>
      <div class='header-fixed-logo'>
        <a class='baguette-link' href="/">
          <%= image_tag('logo.png', :class => "logo-baguette-small", :alt => "logo baketabaguette") %>
        </a>
      </div>
      <div class="header-inner-cta">
        <%= link_to t('navbar.order'), order_path, :class => "navbar-baguette-link-cta" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/enterprise.html.erb
<body class="pages-home">
  <%= render './layouts/navbar' %>
  
  <%= render './layouts/footer' %>
</body>

app/views/pages/home.html.erb
<body class="pages-home">
  <%= render './layouts/navbar' %>
  <div class="banner-container">
    <div class="container">
      <!-- <div class="banner banner-top banner-gradient text-center"> -->
      <div class="banner banner-top banner-gradient text-center" style="background-image: url(<%= image_path 'experience4.jpg' %>);">
        <!-- <div id="videoBlock"> 
          <video autoplay loop id="video-background" muted plays-inline>
            <source src="assets/experience.mp4" type="video/mp4">
          </video> -->
        <div class="banner-gradient-shadow home"></div>
          <!-- <div class="banner-content videoMessage"> -->
        <div class="banner-content">
          <h1 class='mathlete'><%= raw t 'home.title' %></h1>
          <h2>
             <%= raw t 'home.h2' %>
          </h2>
          <p>
            <%= raw t 'home.subtitle' %>
            <!-- <span>
              <i class="fa fa-play-circle-o"></i> See our video
              </span> -->
          </p>
        </div>
      </div>
      <div class='banner-cta'>
        <%# link_to raw(t('home.banner-workshop')), workshop_path, class: "banner-cta-item hidden-xs" %>
        <%= link_to raw(t('home.banner-recipe')), recipe_path, class: "banner-cta-item hidden-xs" %>
        <%= link_to raw(t('home.banner-order')), kits_path, class: "btn banner-cta-item btn-danger btn-lg" %>
      </div>
    </div>
  </div>
  <div class="features-wrapper up">
    <div class="container features-container">
      <h2 class='section-title-home'>
        <div class='section-title-home-content' style="font-size:30px;">
          <%= raw t 'home.headline' %>
        </div>
      </h2>
      <div class='features'>
        <div class='feature'>
          <div class='feature-header'>
            <div class='feature-icon yellow'>
              <i class='mdi mdi-timer'></i>
            </div>
            <h2 class='feature-title'>
              <%= raw t 'home.easy' %>
            </h2>
          </div>
          <div class='feature-body'>
            <%= raw t 'home.easytext' %>
            <a href="/recipe"><%= raw t 'home.easydetails' %></a>
            <br></br>
           <!--  <%# raw t 'home.hardtext' %>
            <a href="/recipe#hard-recipe"><%# raw t 'home.harddetails' %></a> -->
          </div>
        </div>
        <div class='feature'>
          <div class='feature-header'>
            <div class='feature-icon green'>
              <i class='mdi mdi-flag-variant'></i>
            </div>
            <h2 class='feature-title'>
              <%= raw t 'home.authentic' %>
            </h2>
          </div>
          <div class='feature-body'>
            <%= raw t 'home.authentictext' %>
          </div>
        </div>
        <div class='feature'>
          <div class='feature-header'>
            <div class='feature-icon purple'>
              <i class='mdi mdi-emoticon-excited'></i>
            </div>
            <h2 class='feature-title'>
              <%= raw t 'home.delicious' %>
            </h2>
          </div>
          <div class='feature-body'>
            <%= raw t 'home.delicioustext' %>
            <a href="https://www.airbnb.fr/experiences/85015"><%= raw t 'home.airbnbreviews' %></a>
            <br>
          </div>
        </div>
      </div>
      <div class="text-center" style="margin-top: 50px;">
        <a class="link-big" href="/recipe"><%= raw t 'home.read' %></a>
      </div>
    </div>
  </div>
  <%= render 'layouts/reviews' %>
  <!-- <div class="quote-overlay">
    <div class="container">
      <div class='quote'>
        <h2 class='section-title-home quote'>
          <div class='section-title-home-content quote-background'>
            BakeTaBaguette is rated <strong>first baking experience</strong> on Tripadvisor
          </div>
        </h2>
        <div class='techcrunch-view hidden-sm hidden-xs'>
          <a href='...' target='_blank'>
          <img src="..." alt="..." />
          </a>
        </div>
      </div>
    </div>
  </div> -->
  <div id="alumni-home">
    <div class="container">
      <h2 class='section-title-home' style="font-size:30px;">
        <div class='section-title-home-content'>
          <%= raw t 'home.baguettes' %>
        </div>
      </h2>
      <p class="text-muted text-center section-title-home-subtitle">
        <%= raw t 'home.baguettes_subtitle' %>
      </p>
      <div class="projects-list">
        <div class="project-item-container">
          <div class="project-item">
            <div class='project-item-head'>
              <div class="project-thumbnail" style="background: url(assets/baguette1.jpg);background-size:cover;background-position:center center;">
              </div>
            </div>
            <div class="project-item-infos">
              <div class="project-item-infos-left">
                <div class="project-item-name">
                  <%= raw t 'home.baguettes_baker1' %> 
                </div>
                <div class="project-item-tagline">
                  <%= raw t 'home.baguettes_baker1_comment' %>
                </div>
              </div>
              <div class="project-item-makers">
                <div class="project-item-maker">
                  <%= image_tag('baker1.jpg', :class => "avatar", :alt => "karla", :srcset => "assets/baker1.jpg 1x, assets/baker1.jpg 2x", :width => "35", :height => "35") %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="project-item-container">
          <div class="project-item">
            <div class='project-item-head'>
              <div class="project-thumbnail" style="background: url(assets/baguette2.jpg);background-size:cover;background-position:center center;">
              </div>
            </div>
            <div class="project-item-infos">
              <div class="project-item-infos-left">
                <div class="project-item-name">
                  <%= raw t 'home.baguettes_baker2' %>
                </div>
                <div class="project-item-tagline">
                  <%= raw t 'home.baguettes_baker2_comment' %>
                </div>
              </div>
              <div class="project-item-makers">
                <div class="project-item-maker">
                  <%= image_tag('baker2.jpg', :class => "avatar", :alt => "jean", :srcset => "assets/baker2.jpg 1x, assets/baker2.jpg 2x", :width => "35", :height => "35") %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="projects-list-inside">
        <div class="project-item-container">
          <div class="project-item">
            <div class='project-item-head'>
              <div class="project-thumbnail" style="background: url(assets/baguette3.png);background-size:cover;background-position:center center;">
              </div>
            </div>
            <div class="project-item-infos">
              <div class="project-item-infos-left">
                <div class="project-item-name">
                  <%= raw t 'home.baguettes_baker3' %> 
                </div>
                <div class="project-item-tagline">
                  <%= raw t 'home.baguettes_baker3_comment' %>
                </div>
              </div>
              <div class="project-item-makers">
                <div class="project-item-maker">
                  <%= image_tag('baker1.jpg', :class => "avatar", :alt => "bryce", :srcset => "assets/baker3.png 1x, assets/baker3.png 2x", :width => "35", :height => "35") %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="project-item-container">
          <div class="project-item">
            <div class='project-item-head'>
              <div class="project-thumbnail" style="background: url(assets/baguette4.jpg);background-size:cover;background-position:center center;">
              </div>
            </div>
            <div class="project-item-infos">
              <div class="project-item-infos-left">
                <div class="project-item-name">
                  <%= raw t 'home.baguettes_baker4' %>
                </div>
                <div class="project-item-tagline">
                  <%= raw t 'home.baguettes_baker4_comment' %>
                </div>
              </div>
              <div class="project-item-makers">
                <div class="project-item-maker">
                  <%= image_tag('baker2.jpg', :class => "avatar", :alt => "", :srcset => "assets/baker4.jpg 1x, assets/baker4.jpg 2x", :width => "35", :height => "35") %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center" id="more-projects">
        <a class="link-big" href="mailto:baketabaguette@gmail.com"><%= raw t 'home.baguettes_more' %></a>
      </div>
    </div>
    <br>
  </div>
  <!-- NEW PICS PARIS -->
  
  <!-- END -->
  <%= render './layouts/footer' %>
</body>